sudo: required
services:
  - docker

before_install:
  - docker build -t faiscodingdocker/react-test -f ./client/Dockerfile.dev
script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t faiscodingdocker/multi-client ./client
  - docker build -t faiscodingdocker/multi-nginx ./nginx
  - docker build -t faiscodingdocker/multi-server ./server
  - docker build -t faiscodingdocker/multi-worker ./worker